-- Run this in Supabase SQL Editor.
create table if not exists profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  username text unique not null,
  created_at timestamptz default now()
);
create table if not exists messages (
  id bigint generated by default as identity primary key,
  sender_id uuid not null references profiles(id) on delete cascade,
  receiver_id uuid not null references profiles(id) on delete cascade,
  content text not null check (char_length(content) > 0 and char_length(content) <= 5000),
  created_at timestamptz default now()
);

alter table profiles enable row level security;
alter table messages enable row level security;

create policy "Profiles are viewable by signed in users"
on profiles for select to authenticated using (true);

create policy "Users can create their own profile"
on profiles for insert to authenticated with check (auth.uid() = id);

create policy "Users can update their own profile"
on profiles for update to authenticated using (auth.uid() = id);

create policy "Users can read their own conversations"
on messages for select to authenticated
using (auth.uid() = sender_id or auth.uid() = receiver_id);

create policy "Users can send messages as themselves"
on messages for insert to authenticated
with check (auth.uid() = sender_id);

-- Automatically create a profile after signup.
create or replace function public.handle_new_user()
returns trigger language plpgsql security definer set search_path = public
as $$
begin
  insert into public.profiles (id, username)
  values (new.id, split_part(new.email, '@', 1) || '_' || substr(new.id::text,1,5))
  on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute procedure public.handle_new_user();

-- Required for the client-side realtime subscription.
alter publication supabase_realtime add table messages;
